name: Build and Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: neksbit.com-dev
      DIST: dist
      REGION: eu-north-1
      DIST_ID: E2JMPF3G816A42
      ENV_FILE_NAME: .env.dev
      NODE_VERSION: 16

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Adding build time
        run: sed -i "s/%%BUILD_TIME%%/$(date -u)/g" 'frontend/public/index.html'

      - name: Replace .env file
        run: |
          mv frontend/${{ env.ENV_FILE_NAME }} frontend/.env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BUILD_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BUILD_USER }}
          aws-region: ${{ env.REGION }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          node --version
          npm ci

      - name: Build Static Website
        working-directory: ./frontend
        run: npm run build:stage

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
